<a href="https://colab.research.google.com/github/Oluyemisi-Awolade/Master-s-Project_Question_Answering_Model/blob/main/Copy_of_Oluyemisi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from bs4 import BeautifulSoup
import pandas as pd
import torch
import time
from transformers import T5ForConditionalGeneration, T5Tokenizer
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader
from transformers import EncoderDecoderCache

In [ ]:
!sudo apt-get update
!sudo apt-get install chromium-browser

!sudo dnf install chromium

Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [1,315 kB]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:10 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [8,677 kB]
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:12 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-upda

In [ ]:

!pip install selenium
!apt-get install -y chromium-chromedriver
!apt-get update
!pip install webdriver-manager
from selenium import webdriver
from selenium.webdriver.chrome.options import Options



# Configure Chrome options for headless browsing
options = Options()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--remote-debugging-port=9222')  # Optional, for debugging
options.binary_location = "/usr/bin/chromium-browser"

# Create the Chrome driver instance
driver = webdriver.Chrome(options=options)

# Function to fetch and parse web page content
def get_page_content_selenium(url):
    driver.get(url)
    time.sleep(5)  # Adjust as needed for page loading
    html_content = driver.page_source
    return BeautifulSoup(html_content, 'html.parser')

# Lists to store extracted data
admissions_process = []
selection_interview = []
scholarships = []
request = []
faculty = []
graduation_ceremony = []
masters = []
agric_business = []
marketing_sales = []  # Renamed from marketing_sales_url for clarity
data_science = []
entrepreneurship_innovation = []
logistic_supply = []
pm = []
dba = []
mba = []
imba = []
executive_education = []
courses = []
tailored_courses = []
enrollment = []
research_center = []
news_events = []
faq = []
contact = []

# URLs for different pages
admissions_process_url = "https://romebusinessschool.ng/admissions-process/"
selection_interview_url = "https://romebusinessschool.ng/selection-interview/"
scholarships_url = "https://romebusinessschool.ng/scholarships/"
request_url = "https://romebusinessschool.ng/request-for-information/"
faculty_url = "https://romebusinessschool.ng/faculty/"
graduation_ceremony_url = "https://romebusinessschool.ng/graduation-ceremony-2/"
masters_url = "https://romebusinessschool.ng/masters/"
agric_business_url = "https://romebusinessschool.ng/master-in-agribusiness-management-2/"
marketing_sales_url = "https://romebusinessschool.ng/master-in-marketing-and-sales/"
data_science_url = "https://romebusinessschool.ng/master-in-data-science/"
entrepreneurship_innovation_url = "https://romebusinessschool.ng/master-in-entrepreneurship-and-innovation-online/"
logistic_supply_url = "https://romebusinessschool.ng/logistic-and-supply-chain-mgt/"
pm_url = "https://romebusinessschool.ng/master-in-project-management/"
dba_url = "https://romebusinessschool.ng/doctor-of-business-administration-dba/"
mba_url = "https://romebusinessschool.ng/master-business-administration/"
imba_url = "https://romebusinessschool.ng/international-master-of-business-administration-imba/"
executive_education_url = "https://romebusinessschool.ng/executive-education/"
courses_url = "https://romebusinessschool.ng/high-specialization-courses/"
tailored_courses_url = "https://romebusinessschool.ng/tailor-made-courses/"
enrollment_url = "http://enrollment.romebusinessschool.ng/"
research_center_url = "https://romebusinessschool.ng/e-research-center-2/"
news_events_url = "https://romebusinessschool.ng/blog/"
faq_url = "https://romebusinessschool.ng/faq/"
contact_url = "https://romebusinessschool.ng/contact-us/"



# Scraping and data extraction with error handling
def scrape_and_store(url, data_list):
    try:
        page_soup = get_page_content_selenium(url)
        for paragraph in page_soup.find_all('p'):
            text = paragraph.get_text()
            data_list.append(text)
    except Exception as e:
        print(f"Error scraping {url}: {e}")

# Scrape all pages
scrape_and_store(admissions_process_url, admissions_process)
scrape_and_store(selection_interview_url, selection_interview)
scrape_and_store(scholarships_url, scholarships)
scrape_and_store(request_url, request)
scrape_and_store(faculty_url, faculty)
scrape_and_store(graduation_ceremony_url, graduation_ceremony)
scrape_and_store(masters_url, masters)
scrape_and_store(agric_business_url, agric_business)
scrape_and_store(marketing_sales_url, marketing_sales)
scrape_and_store(data_science_url, data_science)
scrape_and_store(entrepreneurship_innovation_url, entrepreneurship_innovation)
scrape_and_store(logistic_supply_url, logistic_supply)
scrape_and_store(pm_url, pm)
scrape_and_store(dba_url, dba)
scrape_and_store(mba_url, mba)
scrape_and_store(imba_url, imba)
scrape_and_store(executive_education_url, executive_education)
scrape_and_store(courses_url, courses)
scrape_and_store(tailored_courses_url, tailored_courses)
scrape_and_store(enrollment_url, enrollment)
scrape_and_store(research_center_url, research_center)
scrape_and_store(news_events_url, news_events)
scrape_and_store(faq_url, faq)
scrape_and_store(contact_url, contact)

# Close the web driver
driver.quit()

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 102.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 492.9/492.9 kB 40.3 MB/s eta 0:00:00
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  chromium-chromedriver
0 upgraded, 1 newly installed, 0 to remove and 22 not upgraded.
Need to get 2,308 B of archives.
After this operation, 77.8 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 chromium-chromedriver amd64 1:85.0.4183.83-0ubuntu2.22.04.1 [2,308 B]
Fetched 2,308 B in 1s (3,476 B/s)
Selecting previously unselected package chromium-chromedriver.
(Reading database ... 125384 files and directories currently installed.)
Preparing to unpack .../chromium-chromedriver_1%3a85.0.4183.83-0ubuntu2.22.04.1_amd64.deb ...
Unpacking chromium-chromedriver (1:85.0.4183.83-0ubuntu2.22.04.1) ...
Setting up chromium-chromedriver (1:

In [ ]:
!# Create question-answer pairs
questions = []
answers = []

# Admissions Process
for text in admissions_process:
    questions.append("question: What is the admissions process like at Rome Business School? context: " + text)
    answers.append(text)

# Selection Interview
for text in selection_interview:
    questions.append("question: Describe the selection interview process at Rome Business School. context: " + text)
    answers.append(text)

# Scholarships
for text in scholarships:
    questions.append("question: What scholarships are offered by Rome Business School? context: " + text)
    answers.append(text)

# Request for Information
for text in request:
    questions.append("question: How can I request information from Rome Business School? context: " + text)
    answers.append(text)

# Faculty
for text in faculty:
    questions.append("question: Tell me about the faculty at Rome Business School. context: " + text)
    answers.append(text)

# Graduation Ceremony
for text in graduation_ceremony:
    questions.append("question: What is the graduation ceremony like at Rome Business School? context: " + text)
    answers.append(text)

# Masters Programs
for text in masters:
    questions.append("question: What Master's programs are available at Rome Business School? context: " + text)
    answers.append(text)

# Agribusiness Management
for text in agric_business:
    questions.append("question: What is the Master in Agribusiness Management program at Rome Business School? context: " + text)
    answers.append(text)

# Marketing and Sales
for text in marketing_sales:
    questions.append("question: Tell me about the Master in Marketing and Sales program at Rome Business School. context: " + text)
    answers.append(text)

# Data Science
for text in data_science:
    questions.append("question: What is the Master in Data Science program like at Rome Business School? context: " + text)
    answers.append(text)

# Entrepreneurship and Innovation
for text in entrepreneurship_innovation:
    questions.append("question: Describe the Master in Entrepreneurship and Innovation program at Rome Business School. context: " + text)
    answers.append(text)

# Logistic and Supply Chain Management
for text in logistic_supply:
    questions.append("question: What is the Logistic and Supply Chain Management program at Rome Business School? context: " + text)
    answers.append(text)

# Project Management
for text in pm:
    questions.append("question: Tell me about the Master in Project Management program at Rome Business School. context: " + text)
    answers.append(text)

# Doctor of Business Administration (DBA)
for text in dba:
    questions.append("question: What is the Doctor of Business Administration (DBA) program at Rome Business School? context: " + text)
    answers.append(text)

# Master of Business Administration (MBA)
for text in mba:
    questions.append("question: Describe the Master of Business Administration (MBA) program at Rome Business School. context: " + text)
    answers.append(text)

# International MBA (IMBA)
for text in imba:
    questions.append("question: What is the International MBA (IMBA) program at Rome Business School? context: " + text)
    answers.append(text)

# Executive Education
for text in executive_education:
    questions.append("question: What Executive Education programs are offered by Rome Business School? context: " + text)
    answers.append(text)

# Specialization Courses
for text in courses:
    questions.append("question: What High Specialization Courses are available at Rome Business School? context: " + text)
    answers.append(text)

# Tailored Courses
for text in tailored_courses:
    questions.append("question: Tell me about the Tailor-Made Courses at Rome Business School. context: " + text)
    answers.append(text)

# Enrollment
for text in enrollment:
    questions.append("question: How do I enroll in a program at Rome Business School? context: " + text)
    answers.append(text)

# Research Center
for text in research_center:
    questions.append("question: What is the E-Research Center at Rome Business School? context: " + text)
    answers.append(text)

# News and Events
for text in news_events:
    questions.append("question: What are the latest news and events at Rome Business School? context: " + text)
    answers.append(text)

# FAQ
for text in faq:
    questions.append("question: What are some frequently asked questions about Rome Business School? context: " + text)
    answers.append(text)

# Contact
for text in contact:
    questions.append("question: How can I contact Rome Business School? context: " + text)
    answers.append(text)


# Create a Pandas DataFrame
qa_df = pd.DataFrame({'question': questions, 'answer': answers})
qa_df.to_csv('qa_pairs.csv', index=False)


# Read the CSV file into a DataFrame
qa_df = pd.read_csv('qa_pairs.csv')

# Access the questions and answers
questions = qa_df['question'].tolist()
answers = qa_df['answer'].tolist()

# Tokenization
tokenizer = T5Tokenizer.from_pretrained('t5-base')

def tokenize_data(df):
    df['question'] = df['question'].apply(lambda x: tokenizer.encode(str(x), max_length=512, truncation=True, padding='max_length') if pd.notna(x) else [])
    df['answer'] = df['answer'].apply(lambda x: tokenizer.encode(str(x), max_length=512, truncation=True, padding='max_length') if pd.notna(x) else [])
    return df



qa_df = tokenize_data(qa_df)

# Split the data into train, validation, and test sets
train_df, val_df = train_test_split(qa_df, test_size=0.2, random_state=42)
val_df, test_df = train_test_split(val_df, test_size=0.5, random_state=42)

# Save the data
train_df.to_csv('train.csv', index=False)
val_df.to_csv('validation.csv', index=False)
test_df.to_csv('test.csv', index=False)

print("Question-answer pairs data created, tokenized, and saved to CSV files.")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565


Question-answer pairs data created, tokenized, and saved to CSV files.


In [ ]:
from torch.utils.data import Dataset

class QADataset(Dataset):
    def __init__(self, questions, answers, tokenizer, max_length=512):
        self.questions = questions
        self.answers = answers
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.questions)

    def __getitem__(self, idx):
        question = self.questions.iloc[idx]
        answer = self.answers.iloc[idx]

        # Handle potential NaN values in questions or answers
        if not question:
            question = ""  # Replace with an empty string or another appropriate value
        if not answer:
            answer = ""  # Replace with an empty string or another appropriate value

        encoding = self.tokenizer.encode_plus(
            question,
            add_special_tokens=True,
            max_length=self.max_length,
            padding='max_length',
            truncation=True,
            return_attention_mask=True,
            return_tensors='pt'
        )

        decoding = self.tokenizer.encode_plus(
            answer,
            add_special_tokens=True,
            max_length=self.max_length,
            padding='max_length',
            truncation=True,
            return_attention_mask=True,
            return_tensors='pt'
        )

        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'labels': decoding['input_ids'].flatten()
        }

In [ ]:
# Create train and validation datasets
train_dataset = QADataset(train_df['question'], train_df['answer'], tokenizer)
val_dataset = QADataset(val_df['question'], val_df['answer'], tokenizer)
test_dataset = QADataset(test_df['question'], test_df['answer'], tokenizer)

In [ ]:
# Create DataLoader instances
train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=8, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=False)

In [ ]:

# Instantiate the T5 model
model = T5ForConditionalGeneration.from_pretrained('t5-base')
# Check if GPU is available, if not, use CPU
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
    print("WARNING: Using CPU as CUDA is not available. Training will be slower.")

# Move the model to the selected device
model.to(device)

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

T5ForConditionalGeneration(
  (shared): Embedding(32128, 768)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dro

In [ ]:
!nvidia-smi

Tue Feb  4 10:42:26 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   30C    P0             47W /  400W |   40487MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [ ]:
!nvidia-smi --query-gpu=memory.used,memory.total --format=csv,noheader

0 MiB, 40960 MiB


In [ ]:
from transformers import AdamW, get_linear_schedule_with_warmup
from sklearn.metrics import f1_score, accuracy_score, precision_score,recall_score,confusion_matrix

# Define the optimizer and training parameters
optimizer = AdamW(model.parameters(), lr=1e-4)
num_epochs = 10

# Learning rate scheduler
total_steps = len(train_loader) * num_epochs
scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=0, num_training_steps=total_steps)

# Training loop
for epoch in range(num_epochs):
    model.train()
    total_loss = 0

    for batch in train_loader:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        optimizer.zero_grad()

        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss

        loss.backward()
        optimizer.step()
        scheduler.step()  # Update learning rate

        total_loss += loss.item()

    avg_train_loss = total_loss / len(train_loader)
    print(f"Epoch [{epoch+1}/{num_epochs}] Train Loss: {avg_train_loss:.4f}")

# Validation loop
    model.eval()
    with torch.no_grad():
        total_val_loss = 0
        all_predicted_labels = []
        all_true_labels = []

        for batch in val_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss
            total_val_loss += loss.item()

            # For F1-score calculation:
            predicted_labels = torch.argmax(outputs.logits, dim=-1).cpu().numpy().flatten()
            true_labels = batch['labels'].cpu().numpy().flatten()
            all_predicted_labels.extend(predicted_labels)
            all_true_labels.extend(true_labels)

        avg_val_loss = total_val_loss / len(val_loader)
        print(f"Epoch [{epoch+1}/{num_epochs}] Validation Loss: {avg_val_loss:.4f}")

# Calculate and print F1-score for validation set
f1 = f1_score(all_true_labels, all_predicted_labels, average='weighted')
print(f"Epoch [{epoch+1}/{num_epochs}] Validation F1-score: {f1:.4f}")

# Save the fine-tuned model
model.save_pretrained('fine_tuned_t5_model')

/usr/local/lib/python3.11/dist-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.48.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.


Epoch [1/10] Train Loss: 0.2102
Epoch [1/10] Validation Loss: 0.4258
Epoch [2/10] Train Loss: 0.0420
Epoch [2/10] Validation Loss: 0.0337
Epoch [3/10] Train Loss: 0.0224
Epoch [3/10] Validation Loss: 0.0246
Epoch [4/10] Train Loss: 0.0183
Epoch [4/10] Validation Loss: 0.0220
Epoch [5/10] Train Loss: 0.0168
Epoch [5/10] Validation Loss: 0.0204
Epoch [6/10] Train Loss: 0.0156
Epoch [6/10] Validation Loss: 0.0213
Epoch [7/10] Train Loss: 0.0148
Epoch [7/10] Validation Loss: 0.0180
Epoch [8/10] Train Loss: 0.0146
Epoch [8/10] Validation Loss: 0.0171
Epoch [9/10] Train Loss: 0.0144
Epoch [9/10] Validation Loss: 0.0173
Epoch [10/10] Train Loss: 0.0139
Epoch [10/10] Validation Loss: 0.0172
Epoch [10/10] Validation F1-score: 0.9976


In [ ]:

import random
from sklearn.metrics.pairwise import cosine_similarity

# Load the fine-tuned model and tokenizer
model_path = 'fine_tuned_t5_model'  # Path to your saved model
tokenizer = T5Tokenizer.from_pretrained('t5-base')
model = T5ForConditionalGeneration.from_pretrained(model_path)

# Device (CPU or GPU)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)

# Question bank
question_bank = [
    "What are the entry requirements for the Master in Data Science program?",
    "How long does the International MBA (IMBA) program take to complete?",
    "Is the Master in Entrepreneurship and Innovation program offered online?",
    "What types of scholarships are available for international students?",
    "Are there any financial aid options for the DBA program?",
    "Who are some of the faculty members in the Agribusiness Management department?",
    "What research areas does the E-Research Center focus on?",
    "What documents are required for the application process?",
    "When is the deadline for enrolling in the next intake of the MBA program?",
    "Where is the Rome Business School located?",
    "What career services does the school offer?"
]

# Function to generate embeddings using the T5 model
def generate_embeddings(text_list):
    embeddings = []
    for text in text_list:
        input_ids = tokenizer.encode(text, return_tensors="pt").to(device)
        with torch.no_grad():
            # Get hidden states using encoder output instead of model generation
            outputs = model.encoder(input_ids=input_ids, return_dict=True)
            # Reshape embedding to 2D by squeezing the batch dimension
            embedding = outputs.last_hidden_state.mean(dim=1).squeeze(0).cpu().numpy()
            embeddings.append(embedding)
    return embeddings

# Function to retrieve context using semantic similarity
def get_context(question, data_list):
    # 1. Generate embeddings for the data list and the question
    data_embeddings = generate_embeddings(data_list)
    question_embedding = generate_embeddings([question])[0]  # Get the first element

    # 2. Calculate cosine similarity
    similarities = cosine_similarity(question_embedding.reshape(1, -1), data_embeddings).flatten()
    # Reshape question_embedding for cosine_similarity

    # 3. Get the index of the most similar data point
    most_similar_index = similarities.argmax()

    # 4. Return the context
    context = data_list[most_similar_index]
    return context

# Function to get prediction
def get_prediction(question, data_list):
    start_time = time.time()  #
    context = get_context(question, data_list)
    input_text = f"question: {question} context: {context}"
    input_ids = tokenizer.encode(input_text, return_tensors="pt").to(device)
    outputs = model.generate(input_ids,max_length=512, num_beams=6, early_stopping=False)  # Adjusted parameters)
    prediction = tokenizer.decode(outputs[0], skip_special_tokens=True)
    end_time = time.time()
    response_time = end_time - start_time  # Calculate the response time
    print(f"Response Time: {response_time:.4f} seconds")  # Print the response time
    return prediction

# Assuming you have your scraped data in lists like admissions_process, selection_interview, etc.
# Combine all the scraped data into one list
all_data = admissions_process + selection_interview + scholarships + request + faculty + graduation_ceremony + masters + agric_business + marketing_sales + data_science + entrepreneurship_innovation + logistic_supply + pm + dba + mba + imba + executive_education + courses + tailored_courses + enrollment + research_center + news_events + faq + contact

# Example usage with random question and context retrieval
random_question = random.choice(question_bank)
prediction = get_prediction(random_question, all_data) # Uncomment and replace 'all_data'

print(f"Question: {random_question}")
print(f"Prediction: {prediction}") # Uncomment to print the prediction

Response Time: 22.9500 seconds
Question: Where is the Rome Business School located?
Prediction: Nigeria


In [ ]:
# Evaluation on the test set (with F1-score)
model.eval()
with torch.no_grad():
    all_predicted_labels = []  # Reset for test set
    all_true_labels = []  # Reset for test set

    for batch in test_loader:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)

        # For F1-score calculation (test set):
        predicted_labels = torch.argmax(outputs.logits, dim=-1).cpu().numpy().flatten()
        true_labels = batch['labels'].cpu().numpy().flatten()
        all_predicted_labels.extend(predicted_labels)
        all_true_labels.extend(true_labels)

    # Calculate and print F1-score for test set
    f1 = f1_score(all_true_labels, all_predicted_labels, average='weighted', zero_division=0)
    accuracy = accuracy_score(all_true_labels, all_predicted_labels)
    precision = precision_score(all_true_labels, all_predicted_labels, average='weighted', zero_division=0)
    recall = recall_score(all_true_labels, all_predicted_labels, average='weighted', zero_division=0)  # Sensitivity
    conf_matrix = confusion_matrix(all_true_labels, all_predicted_labels)

    print(f"Test F1-score: {f1:.4f}")
    print(f"Test Accuracy: {accuracy:.4f}")
    print(f"Test Precision: {precision:.4f}")
    print(f"Test Recall (Sensitivity): {recall:.4f}")
    print("Confusion Matrix:")
    print(conf_matrix)

Test F1-score: 0.9977
Test Accuracy: 0.9980
Test Precision: 0.9981
Test Recall (Sensitivity): 0.9980
Confusion Matrix:
[[50828     0     0 ...     0     0     0]
 [  100   101     0 ...     0     0     0]
 [    0     0     5 ...     0     0     0]
 ...
 [    0     0     0 ...     1     0     0]
 [    0     0     0 ...     0     1     0]
 [    0     0     0 ...     0     0     1]]
